version: '3.2'
services:
  postgres:
    hostname: postgres
    ports:
      - '5432:5432'
    image: postgres:14
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    # volumes:
    # SQL files mounted to entrypoint folder are run in alphabetical order
    # - ./database/init.sql:/docker-entrypoint-initdb.d/a.sql
    healthcheck:
      test: ['pg_isready', '-h', 'postgres']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
